mutation login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    token
    user {
      id
      email
      username
      birthday
      address {
        id
        zipcode
        addr
        amphoe
        social {
          id
          facebook
          line_id
          etc
        }
      }
      firstname
      lastname
      posts {
        id
        title
        author {
          id
        }
        published
        createdAt
        updatedAt
      }
    }
  }
}
